add authenticated ws support
coinbase-samples/exchange-scripts-py pull request #7
Opened 2023-10-20 21:06 UTC by jc-cb

- add authenticated websocket support

2023-10-24 01:22 UTC, rcbgr approved these changes

2024-02-15 17:05 UTC, rcbgr approved these changes

2024-02-15 18:07 UTC, cfluke-cb requested changes

2024-02-15 18:07 UTC, cfluke-cb commented on websocket/auth_ws_channel.py
> +    return API_KEY, SECRET_KEY, PASSPHRASE, signature_b64, timestamp
you can drop SECRET_KEY as a return value

2024-02-15 18:07 UTC, cfluke-cb commented on websocket/auth_ws_channel.py
> +    return API_KEY, SECRET_KEY, PASSPHRASE, signature_b64, timestamp
actually i would simplify this to only signature_b64 and timestamp. api_key and passphrase can be used as the global constants above

2024-03-27 13:28 UTC, nmorgan-cb approved these changes

2024-03-27 16:00 UTC, cfluke-cb approved these changes

2024-03-27 16:00 UTC, merged

2024-06-04 22:29 UTC, CarolinaMomma843 approved these changes

2024-06-04 22:29 UTC, CarolinaMomma843 approved these changes